# Generated by Django 5.0 on 2024-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('merah', 'Hitam'), ('merah', 'Kuning'), ('merah', 'Hijau'), ('merah', 'Biru'), ('merah', 'Putih'), ('merah', 'Ungu'), ('merah', 'Coklat')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
