# Generated by Django 5.0 on 2024-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('merah', 'Merah'), ('hitam', 'Hitam'), ('kuning', 'Kuning'), ('hijau', 'Hijau'), ('biru', 'Biru'), ('putih', 'Putih'), ('ungu', 'Ungu'), ('coklat', 'Coklat')], max_length=10),
        ),
    ]
